return {
    compostable_items = {
        -- my items
        ["plant-residues"] = 1,
        ["plant-residues-dry"] = 1,
        ["plant-residues-pellets"] = 1,
        ["canola"] = 1,
        ["canola-seed"] = 1,
        ["canola-seed-dry"] = 1,
        ["canola-seed-peeled"] = 1,
        ["canola-meal"] = 1,
        ["cocoa-fruit"] = 1,
        ["cocoa-fruit-washed"] = 1,
        ["cocoa-fruit-roasted"] = 1,
        ["cocoa-beans"] = 1,
        ["coconut"] = 1,
        ["copra"] = 1,
        ["copra-halved"] = 1,
        ["copra-halved-dry"] = 1,
        ["coconut-butter"] = 1,
        ["oil-palm-fruit"] = 1,
        ["oil-palm-fruit-flesh"] = 1,
        ["oil-palm-kernel"] = 1,
        ["oil-palm-kernel-dry"] = 1,
        ["oil-palm-kernel-open"] = 1,
        ["soy-pods"] = 1,
        ["soy-pods-washed"] = 1,
        ["edamame"] = 1,
        ["soy-beans"] = 1,
        ["soy-meal"] = 1,
        ["tofu-block"] = 1,
        ["tempeh"] = 1,
        ["yuba"] = 1,
        ["tiriscefing-willow"] = 1,
        ["tiriscefing-willow-bork"] = 1,
        ["sewage-sludge-dry"] = 1,
        ["solfaen-dry"] = 1,
        ["solfaen-washed"] = 1,
        ["atztazzae-mushroom"] = 1,
        ["atztazzae-mycel"] = 1,
        ["atztazzae-spore"] = 1,
        -- base
        ["wood"] = 1,
        ["raw-fish"] = 1,
        -- pycoal
        ["log"] = 1,
        ["fawogae"] = 1,
        ["ralesia"] = 1,
        ["ralesia-seeds"] = 1,
        ["organic-matter"] = 1,
        ["fawogae-substrate"] = 1,
        -- pyht
        ["bones"] = 1,
        ["zipir-carcass"] = 1,
        ["dried-meat"] = 1,
        ["dry-ralesia"] = 1,
        ["skin"] = 1,
        ["raw-fiber"] = 1, 
        ["ralesia-powder"] = 1,
        -- pyph
        ["guar"] = 1,
        ["guar-seeds"] = 1,
    }
}